### PR TITLE
upgrated to latest fatjar plugin

### PR DESCRIPTION
**Pull request by musketyr**
latest version adds support for Groovy 2.0 ext modules, excluding files
from being processed and fixes problem with excluding particular
dependencies from being bundled into the fat jar

### CODE REVIEW

**Comment by bmuschko** [comment]
Looks like the dependency hadn't fully propagated to Sonartype OSS yet when you created the pull request. It seems to be available now.

**Comment by musketyr** [comment]
your right. just wait a moment. there was a bug merging extension modules
and I'm now waiting if @codeconsole verifies it.

2012/10/25 Benjamin Muschko notifications@github.com

**Comment by bmuschko** [comment]
OK, let me know when it got verified.

**Comment by codeconsole** [comment]
0.2-rc1 works good for me

**Pull request merged**
