### PR TITLE
Runtime optimization

### PR DESCRIPTION
**Pull request by musketyr**
Added optional dependency on [Gradle FatJar Plugin](https://github.com/musketyr/gradle-fatjar-plugin) to allow uploading "Slim WAR".

### CODE REVIEW

**Comment by musketyr** [comment]
@bmuschko any problems with this pull request?

**Comment by bmuschko** [comment]
Sorry, I didn't even find the time to look at this yet. At the moment I am traveling but will be back on Sunday.

**Comment by musketyr** [comment]
ok. have a nice trip.

**Comment by glaforge** [comment]
Not merged yet?

**Comment by bmuschko** [comment]
It's going to come up later today.

**Pull request merged**
