### PR TITLE
Adding ability for the Application and Version information to be overridden for deployment and all other operations

### PR DESCRIPTION
**Pull request by bfschuil**
Use Case:
We are using our CI server's to push our application to multiple environments and do not want to create custom tasks to programatically edit our appengine-web.xml
This change allows us to pass in a project property to override the app engine application id and version number.
Since this information can be used for all the tasks, it made sense to move it up into the appcfg closure and rename the existing app closure to download.

### CODE REVIEW

**Comment by bmuschko** [comment]
I am planning to [hand over the plugin to Google](https://code.google.com/p/googleappengine/issues/detail?id=8834). Can you do me a favor and sign the [Google CLA](https://developers.google.com/open-source/cla/individual)? If you want your change to make it into the "official" Google version of the plugin, you will need to sign it. After signing the CLA, I will merge the pull request.

**Comment by bfschuil** [comment]
Hi Benjamin I signed the Google CLA.
I realised that I didn't update a section of the documentation.

The example section:

gae {
    httpPort = 8085
    optimizeWar = true

```
appcfg {
    email = 'benjamin.muschko@gmail.com'
    passIn = true

    logs {
        severity = 1
        outputFile = file('mylogs.txt')
    }

    app {
        id = 'sample-app'
    }
}
```

}

should actually look like this:

gae {
    httpPort = 8085
    optimizeWar = true

```
appcfg {
    email = 'benjamin.muschko@gmail.com'
    passIn = true
    id = 'myAppId'

    logs {
        severity = 1
        outputFile = file('mylogs.txt')
    }

    download {
        outputDirectory = 'build/myLocation'
    }
}
```

}

If you'd like I can make the changes and submit another pull request for
you.
Thanks!
Ben

Smile :)

**Comment by bmuschko** [comment]
You can just update this pull request. No need to create another one. Thanks!

**Comment by bfschuil** [comment]
I've updated the documentation, and bumped the version to 0.10 after merging the recent changes you've made.  From my end, there are no other changes I'd like to make.

**Comment by mattdoran** [comment]
I was just investigating my own patch for exactly this case.  Any chance of pulling this and doing a release that includes this?

**Comment by bmuschko** [comment]
Sorry for not getting back to you right way. Would you mind opening the pull request against this [repository](https://github.com/GoogleCloudPlatform/gradle-appengine-plugin)? This going to be new mainline for the plugin.

**Comment by bfschuil** [comment]
Ok, I just created a new branch and merged the changes over.  I think I did something weird because it picked up all the previous commit history in my pull request.  However, it is there.  Any idea of how to remove that history? Thanks!

**Comment by bfschuil** [comment]
Figured it out.  I'll close this request when it's accepted in the other location.

**Comment by bmuschko** [comment]
Closing this pull request as the repository is discontinued. Thanks for your contribution.

**Pull request closed without merging**
