### PR TITLE
Issue-52 - Adding support for specifying the `--address` of local dev server

### PR DESCRIPTION
**Pull request by kdabir**
I updated the version in build.gradle and updated the README and REALEAS_NOTES as well.

### CODE REVIEW

**Comment by bmuschko** [comment]
Thanks for the pull request. I am going to review it soon.

**Comment by bmuschko** [comment]
Thanks for your contribution! The new version will be available on Maven Central soon.

**Comment by bmuschko** [comment]
I am planning to [hand over the plugin to Google](https://code.google.com/p/googleappengine/issues/detail?id=8834). Can you do me a favor and sign the [Google CLA](https://developers.google.com/open-source/cla/individual)? If you want your change to make it into the "official" Google version of the plugin, you will need to sign it.

**Comment by kdabir** [comment]
Thank Ben for merging the pull request. I have signed the CLA electronically. Hope to see the change to make it to the official one.

**Pull request merged**
