### PR TITLE
Changing property for build that modifies appengine-web.xml

### PR DESCRIPTION
**Pull request by musketyr**
If the build modifies `appengine-web.xml` config file (e.g. change application version to testing one) commands will use this changed file instead source one if `gae.appcfg.changing = true`

### CODE REVIEW

**Comment by bmuschko** [comment]
I don't really understand the use case for this change. Can you give me more background information on when this situation would occur? Also the user should not have to care whether any internal files changes. Exposing such a functionality allows implementation details to bleed out to the user.

**Comment by musketyr** [comment]
The actual use case is that we have several configuration for different
environments e.g. test, production, stable etc. and the build is able to
overwrite the appengine files. Update tasks work well since they use the
configuration files from exploded war folder but e.g. rollback task won't
work. So for example if your upload task fails you're not able to rollback
it using this plugin.

On the other hand, I'm not against if there is no new property all tasks
use appengine files from the build folder.
 Dne 9.12.2012 15:35 "Benjamin Muschko" notifications@github.com
napsal(a):

**Comment by bmuschko** [comment]
Is it your build that overwrites the appengine files? Maybe you can show me how you do that in your build so I can get a clearer picture.

**Comment by musketyr** [comment]
@bmuschko do we need more discussion on this?

**Comment by ludoch** [comment]
the appcfg tool can override the app name and app version. Maybe these 2 flags could be used (or exposed) via gradle?

**Comment by bmuschko** [comment]
That sounds like a less invasive way to make this work. @musketyr Would that be a viable solution for you?

**Comment by musketyr** [comment]
well, it's viable but not preferred solution. I would have to always check what's the app name and version currently used. on the other hand current solution from this request just works transparently using common plugin tasks.

but :+1: for exposing these properties via gradle (expecially for command line usage)

**Comment by bmuschko** [comment]
Please reopen the pull request against the new [repository](https://github.com/GoogleCloudPlatform/gradle-appengine-plugin). Closing this as development is discontinued in this code base.

**Pull request closed without merging**
